spring:
  application:
    name: event-management

  data:
    mongodb:
      database : EventManagement
      port : 27017
      host : localhost

server:
  port: 8081
  servlet:
    context-path: "/event-management"